// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OffPay.Infrastructure.Persistence.Oracle;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace OffPay.Infrastructure.Persistence.Oracle.Migrations
{
    [DbContext(typeof(OffPayDbContext))]
    [Migration("20260528134348_CriarEsquemaInicial")]
    partial class CriarEsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OffPay.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChavePublicaPem")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("CHAVE_PUBLICA_PEM");

                    b.Property<string>("ComercianteId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("COMERCIANTE_ID");

                    b.Property<DateTime?>("DataBloqueio")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_BLOQUEIO");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_REGISTRO");

                    b.Property<string>("IdentificadorPublico")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("IDENTIFICADOR_PUBLICO");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("MOTIVO_BLOQUEIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorPublico")
                        .IsUnique()
                        .HasDatabaseName("IX_DISP_IDENT_PUBLICO");

                    b.HasIndex("ComercianteId", "Status")
                        .HasDatabaseName("IX_DISP_COMERCIANTE_STATUS");

                    b.ToTable("DISPOSITIVO", (string)null);
                });

            modelBuilder.Entity("OffPay.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DispositivoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("DISPOSITIVO_ID");

                    b.Property<string>("HashAnterior")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("HASH_ANTERIOR");

                    b.Property<string>("HashTransacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("HASH_TRANSACAO");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("LOTE_ID");

                    b.Property<string>("Observacao")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("StatusValidacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(30)")
                        .HasColumnName("STATUS_VALIDACAO");

                    b.Property<DateTime>("TimestampRecebimento")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TIMESTAMP_RECEBIMENTO");

                    b.Property<DateTime>("TimestampTransacao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TIMESTAMP_TRANSACAO");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(64)")
                        .HasColumnName("TRANSACAO_ID");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("IX_LOG_LOTE_ID");

                    b.HasIndex("DispositivoId", "TimestampTransacao")
                        .HasDatabaseName("IX_LOG_DISP_TIMESTAMP");

                    b.ToTable("LOG_AUDITORIA", (string)null);
                });

            modelBuilder.Entity("OffPay.Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("OffPay.Domain.Entities.Dispositivo", "Dispositivo")
                        .WithMany("Logs")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("OffPay.Domain.Entities.Dispositivo", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
